# Site settings
title: Alexis Malagnino
description:  Welcome to my personal website !
img: https://alexismalagnino.netlify.app/assets/preview.png
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Alexis Malagnino
user_description: I'm a Doctor of Biology from France ! My PhD focuses on the influence of environmental constraints on individuals' foraging strategies in an alpine chamois population. In the context of global warming, I have been aiming to understand how individuals may adjust their space use and activity budgets in response to summer extreme temperatures, while still addressing their energetic needs, and investigating the potential opportunity costs related to behavioural thermoregulation.
user_title: Doctor of Biology
email: alexismalagnino@gmail.com
# twitter_username: lorem_ipsum
instagram_username: macmala42
facebook_username: alexis.malagnino
# linkedin_username: murraco
# github_username:  murraco
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src', 'node_modules', 'vendor']
